### ISSUE TITLE
Feature Suggestion: Dynamic tests

### ISSUE THREAD

**Issue by wilfredwee** [nextest-rs/nextest#219]
Hi there, first off: this is a really cool project!

I'd like to suggest a feature that JUnit 5 has introduced, and which I personally use heavily: [Dynamic tests](https://www.baeldung.com/junit5-dynamic-tests)

Essentially, I'd like to build the list of test cases during runtime. This is extremely useful for table-driven tests, and the flexibility of defining tests in runtime allows developers to write more interesting test inputs.

**Comment by sunshowers** [comment]
Thanks for the report! This is outside the scope of nextest since it is a test *runner*, but you could use a custom test framework to achieve this. For an example with a dynamically generated list of files, see https://crates.io/crates/datatest-stable. Otherwise see https://nexte.st/book/custom-test-harnesses.html if you'd like to write your own.

You can use https://crates.io/crates/libtest-mimic to write your own if desired—the latest version is tested to work with nextest.

**Comment by wilfredwee** [comment]
Thanks! Those look like great resources, I might consider writing a custom test harness for dynamic tests :)
