### ISSUE TITLE
Reduce the binary size needed for build reusing

### ISSUE THREAD

**Issue by tabokie** [nextest-rs/nextest#229]
Currently the entire target directory is needed when reusing build on another machine. This is quite a setback for us because previously we only need to transfer a specific test binary under `target/debug/deps/` generated by `cargo test --no-run`.

I'm wondering if it's possible to reduce the binaries that must be shared between two machines, and make this information easy enough to use. Or better yet, package the necessary test artifacts by nextest itself.

This would be especially useful for test partitioning. For our use case, test cases from one large repo are sharded to tens of partitions. With this feature, each partition wouldn't have to download all the test binaries.

**Comment by sunshowers** [comment]
Thanks for the report and I'm really excited to hear about how many partitions you use! I think working on this would be really cool.

Even today, you can definitely just transfer the binaries you need over as long as you maintain the directory structure -- the current recommendation is a really conservative overestimate, since we've found that some tests do need other files in the target directory.

> Or better yet, package the necessary test artifacts by nextest itself.

This would be a fantastic addition. Maybe by adding an `archive` command, and allowing the `run` command to accept a `--test-archive` flag.

> For our use case, test cases from one large repo are sharded to tens of partitions. With this feature, each partition wouldn't have to download all the test binaries.

So this is a separate feature request, which is to allow partitioning by binary (the current partitioning/sharding implementation uses both binary and test names as inputs). That's not done by nextest at the moment but can be added as an option (maybe as part of [filter expressions](https://nexte.st/book/filter-expressions.html)).

How about we try solving the archive problem first and then see if binary partitioning is still required for you?

**Comment by tabokie** [comment]
> the current recommendation is a really conservative overestimate, since we've found that some tests do need other files in the target directory.

Yes, I thought of that too. But it's not very easy to leverage it at the moment, because (1) there is no public documentation to guarantee it's safe and stable to use; (2) it doesn't work well with partitioning (we don't know the exact binaries referenced by a certain partition). So I think adding the archive option is probably a more natural solution.

> How about we try solving the archive problem first and then see if binary partitioning is still required for you?

That would be awesome! I'd love to help.

**Comment by sunshowers** [comment]
Thanks! I'm working on this now, hope to have something in the next couple of days.

**Comment by sunshowers** [comment]
BTW are you using nextest over at Pingcap?

**Comment by tabokie** [comment]
Not at the moment, we are still hand-partitioning the test binaries. But I want to push for adoption if this issue is resolved. The flaky test retry feature is something we'd love to use.

**Comment by sunshowers** [comment]
@tabokie I just released cargo nextest 0.9.15 (it should show up via the release URLs in a few minutes). See https://nexte.st/book/reusing-builds.html#creating-archives -- would be interested to hear how this works for you!

**Comment by tabokie** [comment]
@sunshowers I tried it out, it looks very promising (the filtered files are still a little bloated though, look forward to some improvements there). But unfortunately I hit a bug, the issue is here: https://github.com/nextest-rs/nextest/issues/247.

**Comment by sunshowers** [comment]
Thanks, I'll try and fix that (and improve the error message) in the next couple of days. Looks like the grpcio-sys library is producing linked paths that don't exist on disk, fun.

**Comment by sunshowers** [comment]
Hi @tabokie -- just released cargo-nextest 0.9.16, with a workaround for this issue (now prints a warning and suggests fixing this upstream rather than failing). I also reduced the size of the archive by not recursing into subdirectories of linked paths (I tried it with raft-engine and it appears to shrink the archive by around 3-4x).

**Comment by tabokie** [comment]
That's awesome! I'll try using it in our main repo [tikv](https://github.com/tikv/tikv) next week.

**Comment by sunshowers** [comment]
Could you update the thread when you get a chance? I do believe this is overall done—would be happy to take further suggestions as code contributions though.
