### ISSUE TITLE
ANSI color sequences not compared

### ISSUE THREAD

**Issue by p00f** [nextest-rs/nextest#397]
ANSI color sequences are not considered when comparing two strings.

Steps to reproduce:
1. Clone https://git.sr.ht/~p00f/nextest-bug
2. `cargo test` fails:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/nextest_bug-b58179d0bd9b7432)

running 1 test
test tests::print_color ... FAILED

failures:

---- tests::print_color stdout ----
thread 'tests::print_color' panicked at 'assertion failed: `(left == right)`
  left: `"\u{1b}[30mHello\u{1b}[0m"`,
 right: `"Hello"`', src/lib.rs:7:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::print_color

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--lib'
```
3. `cargo nextest run` passes:
```

    Finished test [unoptimized + debuginfo] target(s) in 0.00s
  Executable unittests src/lib.rs (target/debug/deps/nextest_bug-b58179d0bd9b7432)
    Starting 1 tests across 1 binaries
        PASS [   0.001s] nextest-bug tests::print_color
------------
     Summary [   0.001s] 1 tests run: 1 passed, 0 skipped
```

**Comment by sunshowers** [comment]
Thanks for the report! This isn't a bug in nextest—because of how nextest works, program output goes to an in-memory buffer rather than the terminal. This causes the colored library to disable coloring.

You can usually address this by setting an environment variable. For colored, CLICOLOR_FORCE should do the trick. See https://docs.rs/colored/latest/colored/control/struct.ShouldColorize.html#method.from_env.

**Comment by p00f** [comment]
Thanks

**Comment by p00f** [comment]
I was wondering why I couldn't reproduce this by printing the sequence manually instead of using colored haha
