### ISSUE TITLE
Add support for running tests without building them

### ISSUE THREAD

**Issue by Guiguiprim** [nextest-rs/nextest#44]
This might be a weird request, but:

To optimize CI resources, improve build reproducibility and other things, I have the following setup:
- One CI step: cross compilation for windows from a linux CI runner (using nix-docker image)
- An other CI step: run the tests in a windows VM

Currently I build the tests with `cargo test --no-run` and then execute them without `cargo test` in the VMs (with an ugly script).

If it was possible to:
- `cargo nixtest --no-run` in the CI runner
- copy the `target` folder (or at least the relevant part) in the VM
- `cargo nixtest --no-build` in the VM

It would be really awesome.

As is, I don't know if it would be easily doable. If it is not to complex and an acceptable feature, I might be open in doing it under mentoring.

**Comment by TriplEight** [comment]
Double this, it would be a good feature to share the compiled cache between i.e. 2 test executors.

**Comment by poliorcetics** [comment]
> **The list phase.** `cargo-nextest` first builds all test binaries with `cargo test --no-run`, then queries those binaries to produce a list of all tests within them.

[source](https://nexte.st/book/how-it-works.html#the-nextest-model)

If running the binaries to get the test lisy is necessary, I don't think this will be easy

**Comment by TriplEight** [comment]
It requires handling compile cache**s** carefully.

**Comment by sunshowers** [comment]
Thanks for the feature request! I really like this idea. This is totally possible to do, though somewhat tricky. The main challenge here is how to communicate the list of binaries between the different machines.

The way it would probably have to be done is:
* Build and serialize the list of tests and binaries (the `list` [JSON serialization](https://nexte.st/book/machine-readable.html) would work for this)
* Add a `--test-list` option to `nextest run` that takes, as an argument, the serialized JSON representation. This would be an alternative means to compute the test list, and would be inserted [at this point](https://github.com/nextest-rs/nextest/blob/26356ae332504b8915ee4cca1f958b1e725e1c5d/cargo-nextest/src/dispatch.rs#L346-L347).
* For the situation where test binaries are at a different path, add a `--remap-path-prefix` option (dependent on `--test-list`) that replaces any matching prefixes in the test binaries with the specified one. This should be in the format `--remap-path-prefix FROM=TO`, matching rustc.

Some issues I can imagine you running into, and that I would like to see tests for:
* We need the source `PackageGraph` to set the correct [environment variables](https://nexte.st/book/env-vars.html). The best way to do this is probably to also expect there to be a source checkout available (some tests rely on it anyway).
* Package IDs might be different across machines, because they have the source path in them. To solve this, we'll want to use an alternate ID. You can have a look at [guppy-summaries' `SummaryId`](https://docs.rs/guppy-summaries/latest/guppy_summaries/struct.SummaryId.html) for a path-independent way to identify packages -- maybe it's as simple as just adding a `summary-id` key to the [`RustTestSummary`](https://docs.rs/nextest-metadata/latest/nextest_metadata/struct.RustTestSuiteSummary.html). Then, on the deserializing end, you can use [this method on `PackageGraph`](https://docs.rs/guppy/latest/guppy/graph/struct.PackageGraph.html#method.metadata_by_summary_id) to get the package metadata.
* Different path separators on Windows vs Unix. You may have to convert to or from the native path separator while remapping paths.

As mentioned above, I think this is a bit tricky but totally doable.

I don't think I'm going to get to it any time soon, but @Guiguiprim if you'd like to build this and add proper tests for it, a PR would be welcome! Let me know if you have any further questions, hope this is a good outline.

**Comment by Guiguiprim** [comment]
Thanks for all that input.

In my use case, I do clone the repository inside the VMs (for tests assets)

One small issue that I see with what you said is: As I am cross-compiling, I will be able to get the binaries list, but not the tests list (if I followed correctly, this requires launching the binaries with `--list`, which I can't do as it would require cross-running). I guess we will need to be able to split the `list-tests` logic in two: binaries listing and tests listing.

If I found some time, I going to try to do it.

**Comment by jelmansouri** [comment]
This would be very useful for us since we are cross-compiling from linux to windows. But we also have some GPU dependent tests, this will help us save on GPU machines by a lot!

**Comment by sunshowers** [comment]
Experimental support for this is now out in cargo-nextest 0.9.10! Here's the [documentation](https://nexte.st/book/reusing-builds.html) for this feature, and the tracking issue to stabilize it is #98.

Really excited for people to try this out and provide feedback! Thanks again @Guiguiprim for implementing it.
