### ISSUE TITLE
Turn off progress bar

### ISSUE THREAD

**Issue by remlse** [nextest-rs/nextest#503]
I've been trying to disable the progress bar, as every update to it prints a separate line in CI for me, which massively clutters the output.

I think this should be possible, but I can't figure it out. Either this is not yet implemented, or the documentation could be improved in this regard.

I'd be happy to make this my first contribution in either case.

**Comment by sunshowers** [comment]
Thanks for the report!

That's really weird, the progress bar shouldn't be shown in CI because it's only shown in a terminal, and there's no terminal available there. What CI are you using? I know GitHub Actions works fine.

Regardless, I'd be fine with an environment variable with values always/auto/never. NEXTEST_SHOW_PROGRESS_BAR maybe?

**Comment by remlse** [comment]
I've been trying out CirceCI. I'll try to implement that environment variable!
