### ISSUE TITLE
Is it possible to turn off the zstd dependency using the feature of cargo-nextest?

### ISSUE THREAD

**Issue by Dushistov** [nextest-rs/nextest#671]
Before `0.9.44` I  just use `cargo install cargo-nextest` and pack result on machine with the oldest version of glibc,
and then using archive to deliver cargo-nextest on all machines.

With 0.9.44 I got build error:

```
note: /tmp/cargo-installOCRepy/release/deps/libnextest_runner-5e6fe5cfa35829bf.rlib(nextest_runner-5e6fe5cfa35829bf.nextest_runner.9e60ca36-cgu.4.rcgu.o): In function `zstd_safe::DCtx::decompress_stream':
          nextest_runner.9e60ca36-cgu.4:(.text._ZN9zstd_safe4DCtx17decompress_stream17h2d10e89ddc2fdb69E+0x7a): undefined reference to `ZSTD_decompressStream'
```

I have no idea why "test runner" need compress library, before to find way to install zstd on machine with the oldest version of the glibc (old Linux CentOS),
I tried to build  on my development machine :

```
❯ ls /usr/lib/libzstd*
/usr/lib/libzstd.so  /usr/lib/libzstd.so.1  /usr/lib/libzstd.so.1.5.2

❯ ~/.cargo/bin/cargo-nextest  --version
cargo-nextest 0.9.44

❯ ldd ~/.cargo/bin/cargo-nextest 
        linux-vdso.so.1 (0x00007ffeda708000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ff6231bf000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007ff6230d7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff622ef0000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff623e32000)

```

So resulted binary don't need zstd at all, why I need it during build then?
Can `zstd` be disabled via features of `cargo-nextest` ?

**Comment by sunshowers** [comment]
Thanks for the report!

Nextest uses zstd for the archive and reuse build option: https://nexte.st/book/reusing-builds.html

It statically bundles zstd with the binary, which is why you don't see a dynamic dependency. Nextest is meant to be a mostly-static binary with no dependencies other than the system libc.

There is no way to disable zstd support, nor do we plan to add a way to do that. I think the most productive way forward would be to figure out why your build broke (zstd was added as a dependency [in May](https://github.com/nextest-rs/nextest/commit/0b37fb0578abd3464a2ac7303c266177b9b4c38b) and the version hasn't changed since then). I think the best way to get started with that would be to run a bisect on the repository and identify which commit broke you.

**Comment by sunshowers** [comment]
I'm going to close this issue since it seems to be an environment issue with yours. Please feel free to reopen the issue with more details if you get stuck.
