### ISSUE TITLE
Having a hard time testing the time crate using nextest

### ISSUE THREAD

**Issue by azzamsa** [nextest-rs/nextest#731]
Hi.

`time` can't use the `multithreaded` test as mentioned in https://github.com/time-rs/time/issues/538#issuecomment-1357035400.
Testing the code below using ` cargo test` won't work, it needs to be `cargo test -- --test-threads 1`

```rust
use anyhow::Result;
use time::{Date, OffsetDateTime};

fn date() -> Result<Date> {
    let date = OffsetDateTime::now_local()?.date();
    println!("{:?}", date);
    Ok(date)
}

fn main() {
    if let Err(err) = date() {
        eprintln!("Error: {:?}", err);
    }
}

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use super::*;

    #[test]
    fn test_date() -> Result<()> {
        assert_eq!("2022-12-27", date()?.to_string());
        Ok(())
    }
}
```

However, when using `nextest`. I still get errors with the following attempts (none of them works):

1. `cargo nextest run --test-threads 1`
2. ` threads-required = "num-test-threads"`
3. `threads-required = "num-cpus"`
4. `threads-required = 1` 

Am I missing something?

Thank you for creating `nextest` :heart:

**Comment by sunshowers** [comment]
Could you paste (using gist) the full output and error please? It isn't reasonable to expect me to reproduce all of your steps manually.

**Comment by sunshowers** [comment]
OK, I see what's happening: we don't pass `--test-threads 1` when running tests, and even though it matches exactly one test cargo test still decides to spin up a thread for the test.

I don't think we can change nextest here, since it would be a breaking change that would impose additional requirements on [custom test harnesses](https://nexte.st/book/custom-test-harnesses.html). Honestly I'm really not sure whether the solution chosen by the time crate is reasonable if this sort of restriction exists with it.

**Comment by azzamsa** [comment]
> Please note that I am providing nextest "AS IS", as a gift to you and the rest of the Rust community, with no warranty. Please treat me (and other open source maintainers you don't have a contractual relationship with) as you would treat the giver of a gift to you.

Oh, I am so sorry for any steps missing in my issue. Thank you so much for taking time to create and maintain nextest.

> I don't think we can change nextest here, since it would be a breaking change that would impose additional requirements on [custom test harnesses](https://nexte.st/book/custom-test-harnesses.html)

Thank you.

**Comment by sunshowers** [comment]
https://github.com/time-rs/time/commit/b5c4bc1a5d0309a78a0f2c8316ed6d8028577817 I think this is what you want.

**Comment by sunshowers** [comment]
You can also consider using Chrono rather than the time crate, which uses https://github.com/strawlab/iana-time-zone to get the local time zone. I think this is overall a much better solution.

This is all because of the "tzpocalypse", where it was found that getting the local timezone is unsound on Unix systems. Personally I think this is all an overreaction, but as far as workarounds go I think iana-time-zone is much better than what the time crate is trying to do.

**Comment by azzamsa** [comment]
> You can also consider using Chrono rather than the time crate,

Yes. I have been using both crate in my projects. `chrono` doesn't suffer this `cargo test` issue. 

> This is all because of the "tzpocalypse", where it was found that getting the local timezone is theoretically unsound on Unix systems. Personally I think this is all an overreaction, but as far as workarounds go I think iana-time-zone is much better than what the time crate is trying to do.

Thanks for this thought. It adds more context to my understanding.
